name: build

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            go-github-actions-cache
          tags: |
            type=sha,prefix=

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
